In [1]:
#Aim: To create the dataframe

In [2]:
#Name: Vrushali Uphade
#Roll no: 76
#Sec: A
#Subject: ET-1
#Date:25/8/25

In [2]:
#importing pandas library
import pandas as pd

In [3]:
#Creating Dataframe
df=pd.DataFrame([[10,20,34,55],[30,20,10,90],[20,70,80,90]],
columns=["CD","DBMS","DSS","CAO"])

In [4]:
df

   CD  DBMS  DSS  CAO
0  10    20   34   55
1  30    20   10   90
2  20    70   80   90

In [5]:
df.shape

(3, 4)

In [6]:
df.size

12

In [7]:
df2=pd.DataFrame([[5,6,7,8,9]],columns=["CD","DBMS","DSS","CAO","DM"])

In [8]:
df.ndim

2

In [10]:
df3 = pd.concat([df, df2])

In [11]:
df3

   CD  DBMS  DSS  CAO   DM
0  10    20   34   55  NaN
1  30    20   10   90  NaN
2  20    70   80   90  NaN
0   5     6    7    8  9.0

# Adding rows in the DataFrame

In [12]:
df2=pd.DataFrame([[5,6,7,8]],
columns=["CD","DBMS","DSS","CAO"])

In [13]:
df3 = pd.concat([df, df2], ignore_index=True)

In [14]:
df3

   CD  DBMS  DSS  CAO
0  10    20   34   55
1  30    20   10   90
2  20    70   80   90
3   5     6    7    8

# Adding Attribute(Columns)in the DataFrame name DM

In [15]:
df3["DM"]=[10,20,30,44]

In [16]:
df3

   CD  DBMS  DSS  CAO  DM
0  10    20   34   55  10
1  30    20   10   90  20
2  20    70   80   90  30
3   5     6    7    8  44

# Deleting Record From DataFrame

In [17]:
df4=df3.drop(index=[1])

In [18]:
df4

   CD  DBMS  DSS  CAO  DM
0  10    20   34   55  10
2  20    70   80   90  30
3   5     6    7    8  44

In [19]:
df5=df3.drop(columns=["DM"])

In [20]:
df5

   CD  DBMS  DSS  CAO
0  10    20   34   55
1  30    20   10   90
2  20    70   80   90
3   5     6    7    8

# Finding Mean Of DSS

In [21]:
print("Mean of DSS:",df5["DSS"].mean())

Mean of DSS: 32.75

In [22]:
print("Median of DSS:",df5["DSS"].median())

Median of DSS: 22.0

In [23]:
print("Mode of DSS:",df5["DSS"].mode())

Mode of DSS: 0     7
1    10
2    34
3    80
Name: DSS, dtype: int64

In [24]:
print("Min of DSS:",df5["DSS"].min())

Min of DSS: 7

In [25]:
print("Max of DSS:",df5["DSS"].max())

Max of DSS: 80

In [26]:
Name=["vrushali","radhika","raghav"]
Name

['vrushali', 'radhika', 'raghav']